version: '3.8'

networks:
  laravelnetwork:
    name: laravelnetwork

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravelnetwork

  php: 
    build:
     context: .
     dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravelnetwork

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - laravelnetwork

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
        - mysql
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MSQL_ROOT_PASSWORD: admin 
    networks:
      - laravelnetwork

  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    depends_on:
        - nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./code_server:/config
      - ./src:/config/workspace
    working_dir: /config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - laravelnetwork
  
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravelnetwork
  
  artisan:
    build:
     context: .
     dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravelnetwork

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravelnetwork

  phpunit:
    build:
     context: .
     dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/vendor/bin/phpunit"]
    networks:
      - laravelnetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - laravelnetwork
    